### ISSUE TITLE
Twitter account 'phpnl'

### ISSUE THREAD

**Issue by dennisdegreef** [phpnl/speaker4hire#2]
The website states a 'phpnl' twitter account. While this account is created in 2009 and has never tweeted before, I'm not too sure this is the right account.

So I think we should either point it to a proper account (if it exists), or try to claim it from twitter if it doesn't, or remove the twitter reference from the site.

Thoughts?

**Comment by jaytaph** [comment]
yes

**Comment by dennisdegreef** [comment]
That's a relief
